spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 31822939jnh
    url: jdbc:mysql://127.0.0.1:3306/Web_Development_tech_Course?characterEncoding=utf-8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*xml

